package shoping.model;
// Generated Apr 12, 2019 8:45:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Brands generated by hbm2java
 */
public class Brands  implements java.io.Serializable {


     private int id;
     private String brandName;
     private String status;
     private Set models = new HashSet(0);

    public Brands() {
    }

	
    public Brands(int id, String brandName) {
        this.id = id;
        this.brandName = brandName;
    }
    public Brands(int id, String brandName, String status, Set models) {
       this.id = id;
       this.brandName = brandName;
       this.status = status;
       this.models = models;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getModels() {
        return this.models;
    }
    
    public void setModels(Set models) {
        this.models = models;
    }




}


