package shoping.model;
// Generated Apr 12, 2019 8:45:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Inventory generated by hbm2java
 */
public class Inventory  implements java.io.Serializable {


     private int id;
     private Products products;
     private String sku;
     private float cost;
     private int quantity;
     private Date datePurchase;

    public Inventory() {
    }

    public Inventory(int id, Products products, String sku, float cost, int quantity, Date datePurchase) {
       this.id = id;
       this.products = products;
       this.sku = sku;
       this.cost = cost;
       this.quantity = quantity;
       this.datePurchase = datePurchase;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public String getSku() {
        return this.sku;
    }
    
    public void setSku(String sku) {
        this.sku = sku;
    }
    public float getCost() {
        return this.cost;
    }
    
    public void setCost(float cost) {
        this.cost = cost;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public Date getDatePurchase() {
        return this.datePurchase;
    }
    
    public void setDatePurchase(Date datePurchase) {
        this.datePurchase = datePurchase;
    }




}


