package shoping.model;
// Generated Apr 12, 2019 8:45:46 PM by Hibernate Tools 4.3.1



/**
 * LikeProducts generated by hbm2java
 */
public class LikeProducts  implements java.io.Serializable {


     private int id;
     private Products products;
     private User user;

    public LikeProducts() {
    }

    public LikeProducts(int id, Products products, User user) {
       this.id = id;
       this.products = products;
       this.user = user;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


