package shoping.model;
// Generated Apr 12, 2019 8:45:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Model generated by hbm2java
 */
public class Model  implements java.io.Serializable {


     private int id;
     private Brands brands;
     private String modelName;
     private String status;
     private Set productses = new HashSet(0);

    public Model() {
    }

	
    public Model(int id, Brands brands, String modelName, String status) {
        this.id = id;
        this.brands = brands;
        this.modelName = modelName;
        this.status = status;
    }
    public Model(int id, Brands brands, String modelName, String status, Set productses) {
       this.id = id;
       this.brands = brands;
       this.modelName = modelName;
       this.status = status;
       this.productses = productses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Brands getBrands() {
        return this.brands;
    }
    
    public void setBrands(Brands brands) {
        this.brands = brands;
    }
    public String getModelName() {
        return this.modelName;
    }
    
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }




}


