package shoping.model;
// Generated Apr 12, 2019 8:45:46 PM by Hibernate Tools 4.3.1



/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails  implements java.io.Serializable {


     private int id;
     private Ordes ordes;
     private Products products;
     private int quantity;
     private float price;
     private String status;
     private float cost;

    public OrderDetails() {
    }

    public OrderDetails(int id, Ordes ordes, Products products, int quantity, float price, String status, float cost) {
       this.id = id;
       this.ordes = ordes;
       this.products = products;
       this.quantity = quantity;
       this.price = price;
       this.status = status;
       this.cost = cost;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Ordes getOrdes() {
        return this.ordes;
    }
    
    public void setOrdes(Ordes ordes) {
        this.ordes = ordes;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public float getCost() {
        return this.cost;
    }
    
    public void setCost(float cost) {
        this.cost = cost;
    }




}


