package shoping.model;
// Generated Apr 12, 2019 8:45:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private int id;
     private Categories categories;
     private Model model;
     private String productName;
     private float price;
     private String status;
     private int likeCount;
     private Set characteristicses = new HashSet(0);
     private Set likeProductses = new HashSet(0);
     private Set orderDetailses = new HashSet(0);
     private Set inventories = new HashSet(0);

    public Products() {
    }

	
    public Products(int id, Categories categories, Model model, String productName, float price, String status, int likeCount) {
        this.id = id;
        this.categories = categories;
        this.model = model;
        this.productName = productName;
        this.price = price;
        this.status = status;
        this.likeCount = likeCount;
    }
    public Products(int id, Categories categories, Model model, String productName, float price, String status, int likeCount, Set characteristicses, Set likeProductses, Set orderDetailses, Set inventories) {
       this.id = id;
       this.categories = categories;
       this.model = model;
       this.productName = productName;
       this.price = price;
       this.status = status;
       this.likeCount = likeCount;
       this.characteristicses = characteristicses;
       this.likeProductses = likeProductses;
       this.orderDetailses = orderDetailses;
       this.inventories = inventories;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public Model getModel() {
        return this.model;
    }
    
    public void setModel(Model model) {
        this.model = model;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public int getLikeCount() {
        return this.likeCount;
    }
    
    public void setLikeCount(int likeCount) {
        this.likeCount = likeCount;
    }
    public Set getCharacteristicses() {
        return this.characteristicses;
    }
    
    public void setCharacteristicses(Set characteristicses) {
        this.characteristicses = characteristicses;
    }
    public Set getLikeProductses() {
        return this.likeProductses;
    }
    
    public void setLikeProductses(Set likeProductses) {
        this.likeProductses = likeProductses;
    }
    public Set getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set orderDetailses) {
        this.orderDetailses = orderDetailses;
    }
    public Set getInventories() {
        return this.inventories;
    }
    
    public void setInventories(Set inventories) {
        this.inventories = inventories;
    }




}


