package shoping.model;
// Generated Apr 12, 2019 8:45:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private Roles roles;
     private String email;
     private String encryptedPassword;
     private Date rememberCreateAt;
     private String userName;
     private Set ordeses = new HashSet(0);
     private Set likeProductses = new HashSet(0);

    public User() {
    }

	
    public User(int id, Roles roles, String email, String encryptedPassword, String userName) {
        this.id = id;
        this.roles = roles;
        this.email = email;
        this.encryptedPassword = encryptedPassword;
        this.userName = userName;
    }
    public User(int id, Roles roles, String email, String encryptedPassword, Date rememberCreateAt, String userName, Set ordeses, Set likeProductses) {
       this.id = id;
       this.roles = roles;
       this.email = email;
       this.encryptedPassword = encryptedPassword;
       this.rememberCreateAt = rememberCreateAt;
       this.userName = userName;
       this.ordeses = ordeses;
       this.likeProductses = likeProductses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getEncryptedPassword() {
        return this.encryptedPassword;
    }
    
    public void setEncryptedPassword(String encryptedPassword) {
        this.encryptedPassword = encryptedPassword;
    }
    public Date getRememberCreateAt() {
        return this.rememberCreateAt;
    }
    
    public void setRememberCreateAt(Date rememberCreateAt) {
        this.rememberCreateAt = rememberCreateAt;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public Set getOrdeses() {
        return this.ordeses;
    }
    
    public void setOrdeses(Set ordeses) {
        this.ordeses = ordeses;
    }
    public Set getLikeProductses() {
        return this.likeProductses;
    }
    
    public void setLikeProductses(Set likeProductses) {
        this.likeProductses = likeProductses;
    }




}


